# Generated by Django 4.1.3 on 2022-11-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gamer',
        ),
    ]
